version: '2'
services:
  vm:
    image: mltooling/ml-workspace-gpu:0.9.1    # 基于的镜像文件
    restart: always
    stdin_open: true
    tty: true
    #runtime: nvidia
    shm_size: 8G
    ports:
       - "24032:22"             # 用于ssh登录
       - "24033:80"
       - "24034:8080"           # jupyter server
       - "24035:8888"
       - "24036:20000"          # shadowsocks client port via tcp
       - "24036:20000/udp"      # shadowsocks client port via udp
    volumes:
      # - ics_home_data:/root   # 这个是上边创建的卷，将ics_home_data修改为自己的卷名
      - /mnt/hdd/pyc:/mnt/hdd   # 注意将ics修改为自己的名字
      - /mnt/hdd/public:/mnt/hdd/public
      - /mnt/ssd.user/pyc:/mnt/ssd
      - /mnt/ssd.public:/mnt/public
      - /mnt/ssd.user/pyc/ml-workspace:/workspace
    environment:
      # 可见的显卡id，可以和其他容器重叠，只是在多个容器同时使用一张卡计算的时候可能会造成冲突。
      - NVIDIA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7,8,9
      - WORKSPACE_AUTH_USER="pyc"
      - WORKSPACE_AUTH_PASSWORD="pycPYC5279101"
      - WORKSPACE_SSL_ENABLED=true
      - INCLUDE_TUTORIALS=false
      - MAX_NUM_THREADS=5
      - SHUTDOWN_INACTIVE_KERNELS=true
      - CONFIG_BACKUP_ENABLED=false