version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'pyc'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pyc5279101'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pycPYC5279101'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '24306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - pyc-mysql-data:/var/lib/mysql
# Names our volume
volumes:
  pyc-mysql-data: